# Numpy

In [6]:
import numpy as np

In [2]:
print("Hello World")

Hello World


In [8]:
myarr = np.array([[3,7,15,25,32]], np.int64)

In [9]:
myarr[0,1]

7

In [10]:
myarr.shape

(1, 5)

In [11]:
myarr.dtype

dtype('int64')

In [12]:
myarr[0,1] = 5

In [13]:
myarr

array([[ 3,  5, 15, 25, 32]], dtype=int64)

 # Array Creation : Conversion from other Python structures

In [14]:
listarray = np.array([[1,2,3], [5,7,8], [0,4,6]])

In [15]:
listarray

array([[1, 2, 3],
       [5, 7, 8],
       [0, 4, 6]])

In [17]:
listarray.shape

(3, 3)

In [19]:
listarray.dtype

dtype('int32')

In [20]:
listarray.size

9

In [22]:
np.array({23,25,25})

array({25, 23}, dtype=object)

In [26]:
zeros = np.zeros((2,5))

In [27]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
rng = np.arange(15)

In [30]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
lspace = np.linspace(1,5,4)

In [36]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [38]:
emp = np.empty((4,6))

In [39]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.37961641e-306,
        2.22518251e-306, 1.33511969e-306, 1.24610383e-306],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.02361614e-306, 1.78020848e-306],
       [1.78021527e-306, 1.69119330e-306, 1.42417629e-306,
        8.45593934e-307, 6.89805151e-307, 9.79101082e-307],
       [1.78020576e-306, 2.22522597e-306, 1.33511969e-306,
        8.90071135e-308, 8.45610231e-307, 0.00000000e+000]])

In [40]:
emp_like = np.empty_like(lspace)

In [41]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [45]:
ide = np.identity(45)

In [46]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [47]:
ide.shape

(45, 45)

In [7]:
arr = np.arange(99)

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [9]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [10]:
arr = arr.ravel()

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])